# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4f1329071e027635104feb3090a0dda02d80a965438d82b8140b49d5f809f27cd06fea14ab862cb27accb8c77ec09e4a2858149eebedbce633a6c567f1f1e0c

test:
  secret_key_base: b12d5ec017b769ec3dbb57fdc29921cdcde26cebf5c16be3c10c1ec647527adc3b50a68ba2ac14362d5407325e16d75fb0d4011eb81799174cd5b5cd6fcc3c3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f4f1329071e027635104feb3090a0dda02d80a965438d82b8140b49d5f809f27cd06fea14ab862cb27accb8c77ec09e4a2858149eebedbce633a6c567f1f1e0c
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
